### ISSUE TITLE
feature request: loopback test

### ISSUE THREAD

**Issue by iddq** [kcuzner/avrdude#11]
Hello,

Can you please implement a loopback test function that can test the programmer hardware if the MISO and MOSI lines are shorted?

Thanks

ps: I'm using usbtiny

**Comment by kcuzner** [comment]
This repository just deals with the `linuxspi` programmer type since the maintainers have not yet seen fit to integrate it into the mainline branch. Your feature request is probably better suited here at the main repository: http://savannah.nongnu.org/projects/avrdude/
