### ISSUE TITLE
Add a license file etc

### ISSUE THREAD

**Issue by E3V3A** [kcuzner/avrdude#19]
You've done quite a bit of improvements, so for others to follow, we may consider cleaning up the repo a bit, by removing old logs, and outdated/ not used text files and move them into some folder. adding a license file is also essential.

**Comment by kcuzner** [comment]
License file: [avrdude/COPYING](https://github.com/kcuzner/avrdude/blob/master/avrdude/COPYING)

As for the other things, this repo is meant to stay more or less in sync with this one: https://savannah.nongnu.org/projects/avrdude/

If you'd like to see changes like that I suggest making them to the parent repo over at savannah. This repo only contains the changes necessary for the linuxspi programmer type.

**Comment by E3V3A** [comment]
Thanks. Yes I found it's GPLv2, and missed the COPYING, blindly expecting LICENSE...

Yeah, I was looking at the Savannah, but I am against using obscure self hosted svn's. It makes it harder and less interesting for people to contribute, where it is harder to track, post and resolve issues. Also seem that github and possibly bitbucket is the modern standard for keeping and actively maintaining repos. I'd rather hope the savannah people would come to their senses and move over here.
